// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajnomhvlzalaxjmzkmpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqbm9taHZsemFsYXhqbXprbXBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDQzODEsImV4cCI6MjA2NzIyMDM4MX0.lI9_MLe2sD7znmVqrEA4d5kToCnj_ewzrwk_nfxJzuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});